### ISSUE TITLE
This variable is not defined anywhere

### ISSUE THREAD

**Issue by blaquee** [objective-see/ProcessMonitor#1]
https://github.com/objective-see/ProcessMonitor/blob/9309f85213c81a93f6f367309d76292f6607cb95/Library/Source/Process.m#L154

**Comment by objective-see** [comment]
fixed in c3b9bda2668a4f27ef46b31064c02ee7b76fbedc

see: https://github.com/objective-see/ProcessMonitor/blob/c3b9bda2668a4f27ef46b31064c02ee7b76fbedc/Library/Source/Process.m#L19
