### ISSUE TITLE
Must SIP be disabled for this to run?

### ISSUE THREAD

**Issue by jayhorowitz** [objective-see/ProcessMonitor#3]
I followed the prompt displayed by the app, but received this error in 10.15.7:

> ProcessMonitor[90013:2788609] ES_NEW_CLIENT_RESULT_ERR_NOT_PERMITTED: "The caller is not permitted to connect. They lack Transparency, Consent, and Control (TCC) approval form the user.

**Comment by cocos543** [comment]
Yep.

**Comment by objective-see** [comment]
No, it can run while SIP is enabled. 

Please following the instructions here: [https://objective-see.com/products/utilities.html](https://objective-see.com/products/utilities.html)
...which include the (Apple required) prerequisite of giving `Terminal.app` Full Disk Access

![](https://objective-see.com/images/UT/fdAccess.png)

**Comment by cocos543** [comment]
No, it can't be run in M1 MacOS11.5 when SIP is Enable~ 

2021-09-14 17:19:15.620 ProcessMonitor[9202:55041] ERROR: es_new_client() failed
2021-09-14 17:19:15.620 ProcessMonitor[9202:55041] ES_NEW_CLIENT_RESULT_ERR_NOT_ENTITLED: "The caller is not properly entitled to connect"

**Comment by objective-see** [comment]
@cocos543
....you just have to give Terminal.app full disk access (as noted above), then it will work even with SIP enabled.


See below:
![image](https://user-images.githubusercontent.com/11327812/133321855-c4fdb6e7-fa6c-428c-bc82-723cbb116456.png)
