### ISSUE TITLE
zzh: command not found 

### ISSUE THREAD

**Issue by avincent98144** [objective-see/ProcessMonitor#9]
![Screenshot 2022-11-15 at 10 35 58 AM](https://user-images.githubusercontent.com/65172111/201999096-a145491a-b744-4926-b136-15982fadf440.jpg)
 
A bug with 13.2 beta 2?

**Comment by keith** [comment]
It doesn't look like you're in the /Applications directory? If not you'll need to specify the absolute path

**Comment by avincent98144** [comment]
.. oh hell .. didn't even notice that as I was racing thru ;-)
